# Generated by Django 5.1.1 on 2024-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0004_author_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Имя'),
        ),
    ]
