# Generated by Django 5.1.1 on 2024-09-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0005_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(db_index=True, help_text='Введите email*', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(editable=False, error_messages={'blank': 'Поле обязательно к заполнению (*)'}, help_text='Введите website*', max_length=100),
        ),
    ]
