# Generated by Django 5.1.1 on 2024-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0007_alter_author_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(error_messages={'blank': 'Поле обязательно к заполнению (*)'}, help_text='Введите website*', max_length=100),
        ),
    ]
