# Generated by Django 5.1.1 on 2024-09-11 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0008_alter_author_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, error_messages={'blank': 'Поле обязательно к заполнению (*)'}, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
