# Generated by Django 5.1.1 on 2024-09-12 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0010_book_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="Director's Name")),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='net_worth',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='positive_review',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='net_worth',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='positive_review',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(db_index=True, help_text='введите мэйл', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(error_messages={'blank': 'Поле не может быть пустым'}, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('love', 'Love'), ('science', 'Science')], default='no genre', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Movie Title')),
                ('directors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='myfirst_app.director')),
            ],
        ),
    ]
