# Generated by Django 5.1.1 on 2024-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0011_director_author_age_author_net_worth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания записи', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='enter_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
